#!/bin/bash -ex

# okf structure is generated by using Gemini

# gcloud config set compute/region us-central1

# build kcmd
git clone https://github.com/GoogleCloudPlatform/knowledge-catalog
cd toolbox/mdcode
npm install 
npm run build # this will build the kcmd command in dist folder

if ! gcloud dataplex entry-groups describe xiaomi-ontology --location=us-central1 --project=lufeng-demo &>/dev/null; then
  gcloud dataplex entry-groups create xiaomi-ontology --location=us-central1 --project=lufeng-demo
fi

/Users/lufengsh/work/knowledge-catalog/toolbox/mdcode/dist/kcmd init --kb lufeng-demo.us-central1.xiaomi-ontology
/Users/lufengsh/work/knowledge-catalog/toolbox/mdcode/dist/kcmd push